modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"

[[mods]]
modId="voxeltools"
version="${file.jarVersion}"
displayName="Voxel Tools"
authors="sciwhiz12" #optional
description='''
Adds powerful tools from the Voxel Box.
'''

[[dependencies.voxeltools]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.0,)"
    side="BOTH"
    
[[dependencies.voxeltools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    side="BOTH"
